baseURL = "/"
languageCode = "en-us"
title = "Mollee Jain"
theme = "hugo-coder"

defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[blackfriday]
  hrefTargetBlank = true

# Note: paths are relative to content
[params]
    author = "Mollee Jain"
    info = "Software Engineer"
    blurb = """Hello World, I'm Mollee! I am currently a software engineer at Microsoft and 
    a STEM education advocate at Nuevo Foundation. Welcome to my site! """
    description = "Mollee Jain's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/profile_main.png"
    # gravatar = "mjain2@wellesley.edu"
    
    blogTitle = """ """
    blogDesc = """I'm figuring things out as I go, and sometimes I write about it!"""

    favicon_32 = "/images/icons/favicon-32x32.png"
    favicon_16 = "/images/icons/favicon-16x16.png"

    dateformat = "January 2, 2006"

    # footercontent = "Figuring it out as I go."

    hidecredits = false
    hidecopyright = false

    rtl = false
    math = true
    custom_css = ["/css/default-css.css"]
    # disable_comments = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/mjain2/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/molleejain"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/MolleeJain"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url = "/posts/"
[[menu.main]]
    name = "LinkedIn"
    pre = "fab fa-linkedin fa-lg"
    weight = 4
    url = "https://www.linkedin.com/in/molleejain"
[[menu.main]]
    name = "Github"
    pre = "fab fa-github fa-lg"
    weight = 5
    url = "https://github.com/mjain2/"
[[menu.main]]
    name = "Twitter"
    pre = "fab fa-twitter fa-lg"
    weight = 6
    url = "https://twitter.com/MolleeJain"